'use strict';

angular.module('cascadeddApp')
  .factory('Customers', function () {
    return [
{
            "accounts" : [ 
                {
                    "bill_to" : "WA0477",
                    "print_lines" : "B",
                    "phone_number" : "4102472424",
                    "ftp_user_id" : "abcsup",
                    "terms" : "1/10 N30",
                    "tax_exempt_number" : "3142088",
                    "ack_fax_number" : "14102475476",
                    "delivery_time1" : "1000",
                    "credit_limit" : 15000,
                    "delivery_time2" : "700",
                    "rec_update_date" : "2016-01-14",
                    "customer_type_code" : "A",
                    "account_id" : "WA0477",
                    "msa_secret" : 0,
                    "status" : "A",
                    "taxable" : 0,
                    "delivery_day1" : "Monday",
                    "msp_block" : 1,
                    "delivery_day2" : "Monday",
                    "account_name" : "#020 BALTIMORE MD",
                    "accounts_id" : 1752,
                    "wizard_trained" : 1,
                    "how_ship" : "Our Truck",
                    "addresses" : [ 
                        {
                            "bill_to_addr_orig_system_ref" : "WA0477-0000-036",
                            "bill_to_cust_orig_system" : "NC",
                            "shipping_instructions" : "\r\n",
                            "ship_to_flag" : "N",
                            "bill_to_cust_org_sys_ref" : "WA0477-036",
                            "state" : "MD",
                            "address1" : "5800 COLUMBIA PARK RD",
                            "bill_to_addr_orig_system" : "NC",
                            "address_status" : "A",
                            "city" : "CHEVERLY",
                            "orig_system_ship_customer" : "NC",
                            "division" : "36",
                            "bill_to_cust_orig_system_ref" : "WA0477-036",
                            "bill_to_addr_org_sys" : "NC",
                            "primary_flag" : 0,
                            "oracle_account_number" : "6257",
                            "orig_system_ship_customer_ref" : "WA0477-036",
                            "org_system_ship_customer_ref" : "WA0477-036",
                            "bill_to_addr_org_sys_ref" : "WA0477-0000-036",
                            "division_code" : "36",
                            "addressid" : "4910",
                            "account_number" : "6257",
                            "modify_date" : "2008-02-29",
                            "oracle_account_name" : "ABC SUPPLY CO INC",
                            "bill_to_cust_org_sys" : "NC",
                            "org_system_ship_customer" : "NC",
                            "country" : "US",
                            "ship_id" : "0",
                            "county" : "PRINCE GEORGES",
                            "postal_code" : "20785",
                            "trans_type" : "S",
                            "bill_to_flag" : "Y",
                            "legacy_account" : "WA0477-036"
                        }
                    ],
                    "po_approval_amount" : 20000,
                    "on_line" : 1,
                    "store_xref" : "WA0477",
                    "address_id" : 2900,
                    "plant_id" : 1,
                    "shipping_address_id" : 0,
                    "energy_up_charge" : 0,
                    "rebate" : "N",
                    "norrey_edi" : 0,
                    "cutoff2" : 9,
                    "cutoff1" : 9,
                    "buyers_name" : "Jerry Gorombol",
                    "ship_code" : 0,
                    "ftp_password" : "awd0430",
                    "credit_consolidation" : "WA0460",
                    "plan_region" : "M3",
                    "thermal_delivery2" : 0,
                    "inv_fax_number" : "3013869312",
                    "price_code" : "C",
                    "thermal_delivery1" : 0,
                    "fob" : "DELIVERED",
                    "route" : "34770",
                    "thermal_cutoff2" : 0,
                    "thermal_cutoff1" : 0,
                    "dist_type" : "D1",
                    "ship_xref" : "WA0477",
                    "shipping_inst_id" : 0,
                    "delivery1" : 2,
                    "mkt_type" : "NC3",
                    "msp_allowance" : 2728,
                    "delivery2" : 2
                },{
                    "bill_to" : "WA0477",
                    "print_lines" : "B",
                    "phone_number" : "4102472424",
                    "ftp_user_id" : "abcsup",
                    "terms" : "1/10 N30",
                    "tax_exempt_number" : "3142088",
                    "ack_fax_number" : "14102475476",
                    "delivery_time1" : "1000",
                    "credit_limit" : 15000,
                    "delivery_time2" : "700",
                    "rec_update_date" : "2016-01-14",
                    "customer_type_code" : "A",
                    "account_id" : "WA0477",
                    "msa_secret" : 0,
                    "status" : "A",
                    "taxable" : 0,
                    "delivery_day1" : "Monday",
                    "msp_block" : 1,
                    "delivery_day2" : "Monday",
                    "account_name" : "#020 BALTIMORE MD",
                    "accounts_id" : 1752,
                    "wizard_trained" : 1,
                    "how_ship" : "Our Truck",
                    "addresses" : [ 
                        {
                            "bill_to_addr_orig_system_ref" : "WA0477-0000-036",
                            "bill_to_cust_orig_system" : "NC",
                            "shipping_instructions" : "\r\n",
                            "ship_to_flag" : "N",
                            "bill_to_cust_org_sys_ref" : "WA0477-036",
                            "state" : "MD",
                            "address1" : "5800 COLUMBIA PARK RD",
                            "bill_to_addr_orig_system" : "NC",
                            "address_status" : "A",
                            "city" : "CHEVERLY",
                            "orig_system_ship_customer" : "NC",
                            "division" : "36",
                            "bill_to_cust_orig_system_ref" : "WA0477-036",
                            "bill_to_addr_org_sys" : "NC",
                            "primary_flag" : 0,
                            "oracle_account_number" : "6257",
                            "orig_system_ship_customer_ref" : "WA0477-036",
                            "org_system_ship_customer_ref" : "WA0477-036",
                            "bill_to_addr_org_sys_ref" : "WA0477-0000-036",
                            "division_code" : "36",
                            "addressid" : "4910",
                            "account_number" : "6257",
                            "modify_date" : "2008-02-29",
                            "oracle_account_name" : "ABC SUPPLY CO INC",
                            "bill_to_cust_org_sys" : "NC",
                            "org_system_ship_customer" : "NC",
                            "country" : "US",
                            "ship_id" : "0",
                            "county" : "PRINCE GEORGES",
                            "postal_code" : "20785",
                            "trans_type" : "S",
                            "bill_to_flag" : "Y",
                            "legacy_account" : "WA0477-036"
                        }
                    ],
                    "po_approval_amount" : 20000,
                    "on_line" : 1,
                    "store_xref" : "WA0477",
                    "address_id" : 2900,
                    "plant_id" : 1,
                    "shipping_address_id" : 0,
                    "energy_up_charge" : 0,
                    "rebate" : "N",
                    "norrey_edi" : 0,
                    "cutoff2" : 9,
                    "cutoff1" : 9,
                    "buyers_name" : "Jerry Gorombol",
                    "ship_code" : 0,
                    "ftp_password" : "awd0430",
                    "credit_consolidation" : "WA0460",
                    "plan_region" : "M3",
                    "thermal_delivery2" : 0,
                    "inv_fax_number" : "3013869312",
                    "price_code" : "C",
                    "thermal_delivery1" : 0,
                    "fob" : "DELIVERED",
                    "route" : "34770",
                    "thermal_cutoff2" : 0,
                    "thermal_cutoff1" : 0,
                    "dist_type" : "D1",
                    "ship_xref" : "WA0477",
                    "shipping_inst_id" : 0,
                    "delivery1" : 2,
                    "mkt_type" : "NC3",
                    "msp_allowance" : 2728,
                    "delivery2" : 2
                },{
                    "bill_to" : "WA0477",
                    "print_lines" : "B",
                    "phone_number" : "4102472424",
                    "ftp_user_id" : "abcsup",
                    "terms" : "1/10 N30",
                    "tax_exempt_number" : "3142088",
                    "ack_fax_number" : "14102475476",
                    "delivery_time1" : "1000",
                    "credit_limit" : 15000,
                    "delivery_time2" : "700",
                    "rec_update_date" : "2016-01-14",
                    "customer_type_code" : "A",
                    "account_id" : "WA0477",
                    "msa_secret" : 0,
                    "status" : "A",
                    "taxable" : 0,
                    "delivery_day1" : "Monday",
                    "msp_block" : 1,
                    "delivery_day2" : "Monday",
                    "account_name" : "#020 BALTIMORE MD",
                    "accounts_id" : 1752,
                    "wizard_trained" : 1,
                    "how_ship" : "Our Truck",
                    "addresses" : [ 
                        {
                            "bill_to_addr_orig_system_ref" : "WA0477-0000-036",
                            "bill_to_cust_orig_system" : "NC",
                            "shipping_instructions" : "\r\n",
                            "ship_to_flag" : "N",
                            "bill_to_cust_org_sys_ref" : "WA0477-036",
                            "state" : "MD",
                            "address1" : "5800 COLUMBIA PARK RD",
                            "bill_to_addr_orig_system" : "NC",
                            "address_status" : "A",
                            "city" : "CHEVERLY",
                            "orig_system_ship_customer" : "NC",
                            "division" : "36",
                            "bill_to_cust_orig_system_ref" : "WA0477-036",
                            "bill_to_addr_org_sys" : "NC",
                            "primary_flag" : 0,
                            "oracle_account_number" : "6257",
                            "orig_system_ship_customer_ref" : "WA0477-036",
                            "org_system_ship_customer_ref" : "WA0477-036",
                            "bill_to_addr_org_sys_ref" : "WA0477-0000-036",
                            "division_code" : "36",
                            "addressid" : "4910",
                            "account_number" : "6257",
                            "modify_date" : "2008-02-29",
                            "oracle_account_name" : "ABC SUPPLY CO INC",
                            "bill_to_cust_org_sys" : "NC",
                            "org_system_ship_customer" : "NC",
                            "country" : "US",
                            "ship_id" : "0",
                            "county" : "PRINCE GEORGES",
                            "postal_code" : "20785",
                            "trans_type" : "S",
                            "bill_to_flag" : "Y",
                            "legacy_account" : "WA0477-036"
                        }
                    ],
                    "po_approval_amount" : 20000,
                    "on_line" : 1,
                    "store_xref" : "WA0477",
                    "address_id" : 2900,
                    "plant_id" : 1,
                    "shipping_address_id" : 0,
                    "energy_up_charge" : 0,
                    "rebate" : "N",
                    "norrey_edi" : 0,
                    "cutoff2" : 9,
                    "cutoff1" : 9,
                    "buyers_name" : "Jerry Gorombol",
                    "ship_code" : 0,
                    "ftp_password" : "awd0430",
                    "credit_consolidation" : "WA0460",
                    "plan_region" : "M3",
                    "thermal_delivery2" : 0,
                    "inv_fax_number" : "3013869312",
                    "price_code" : "C",
                    "thermal_delivery1" : 0,
                    "fob" : "DELIVERED",
                    "route" : "34770",
                    "thermal_cutoff2" : 0,
                    "thermal_cutoff1" : 0,
                    "dist_type" : "D1",
                    "ship_xref" : "WA0477",
                    "shipping_inst_id" : 0,
                    "delivery1" : 2,
                    "mkt_type" : "NC3",
                    "msp_allowance" : 2728,
                    "delivery2" : 2
                }
            ],
            "customers_id" : 444,
            "customer_name" : "ABC SUPPLY",
            "customer_type" : "Ellison",
            "customer_id" : "X_WA",
            "parent_id" : "-",
            "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis nisi quis mi tincidunt luctus ut quis nunc. Nam non risus tincidunt risus sodales condimentum. Morbi sed gravida elit. Nunc a turpis vestibulum elit posuere blandit. Phasellus luctus lectus non porta auctor. Etiam pellentesque imperdiet posuere. Nullam adipiscing congue nisl, in vulputate odio ornare ac."        
        }];

        vm.accounts = [
              {
            "accounts" : [ 
                {
                    "bill_to" : "WA0477",
                    "print_lines" : "B",
                    "phone_number" : "4102472424",
                    "ftp_user_id" : "abcsup",
                    "terms" : "1/10 N30",
                    "tax_exempt_number" : "3142088",
                    "ack_fax_number" : "14102475476",
                    "delivery_time1" : "1000",
                    "credit_limit" : 15000,
                    "delivery_time2" : "700",
                    "rec_update_date" : "2016-01-14",
                    "customer_type_code" : "A",
                    "account_id" : "WA0477",
                    "msa_secret" : 0,
                    "status" : "A",
                    "taxable" : 0,
                    "delivery_day1" : "Monday",
                    "msp_block" : 1,
                    "delivery_day2" : "Monday",
                    "account_name" : "#020 BALTIMORE MD",
                    "accounts_id" : 1752,
                    "wizard_trained" : 1,
                    "how_ship" : "Our Truck",
                    "addresses" : [ 
                        {
                            "bill_to_addr_orig_system_ref" : "WA0477-0000-036",
                            "bill_to_cust_orig_system" : "NC",
                            "shipping_instructions" : "\r\n",
                            "ship_to_flag" : "N",
                            "bill_to_cust_org_sys_ref" : "WA0477-036",
                            "state" : "MD",
                            "address1" : "5800 COLUMBIA PARK RD",
                            "bill_to_addr_orig_system" : "NC",
                            "address_status" : "A",
                            "city" : "CHEVERLY",
                            "orig_system_ship_customer" : "NC",
                            "division" : "36",
                            "bill_to_cust_orig_system_ref" : "WA0477-036",
                            "bill_to_addr_org_sys" : "NC",
                            "primary_flag" : 0,
                            "oracle_account_number" : "6257",
                            "orig_system_ship_customer_ref" : "WA0477-036",
                            "org_system_ship_customer_ref" : "WA0477-036",
                            "bill_to_addr_org_sys_ref" : "WA0477-0000-036",
                            "division_code" : "36",
                            "addressid" : "4910",
                            "account_number" : "6257",
                            "modify_date" : "2008-02-29",
                            "oracle_account_name" : "ABC SUPPLY CO INC",
                            "bill_to_cust_org_sys" : "NC",
                            "org_system_ship_customer" : "NC",
                            "country" : "US",
                            "ship_id" : "0",
                            "county" : "PRINCE GEORGES",
                            "postal_code" : "20785",
                            "trans_type" : "S",
                            "bill_to_flag" : "Y",
                            "legacy_account" : "WA0477-036"
                        }
                    ],
                    "po_approval_amount" : 20000,
                    "on_line" : 1,
                    "store_xref" : "WA0477",
                    "address_id" : 2900,
                    "plant_id" : 1,
                    "shipping_address_id" : 0,
                    "energy_up_charge" : 0,
                    "rebate" : "N",
                    "norrey_edi" : 0,
                    "cutoff2" : 9,
                    "cutoff1" : 9,
                    "buyers_name" : "Jerry Gorombol",
                    "ship_code" : 0,
                    "ftp_password" : "awd0430",
                    "credit_consolidation" : "WA0460",
                    "plan_region" : "M3",
                    "thermal_delivery2" : 0,
                    "inv_fax_number" : "3013869312",
                    "price_code" : "C",
                    "thermal_delivery1" : 0,
                    "fob" : "DELIVERED",
                    "route" : "34770",
                    "thermal_cutoff2" : 0,
                    "thermal_cutoff1" : 0,
                    "dist_type" : "D1",
                    "ship_xref" : "WA0477",
                    "shipping_inst_id" : 0,
                    "delivery1" : 2,
                    "mkt_type" : "NC3",
                    "msp_allowance" : 2728,
                    "delivery2" : 2
                },{
                    "bill_to" : "WA0477",
                    "print_lines" : "B",
                    "phone_number" : "4102472424",
                    "ftp_user_id" : "abcsup",
                    "terms" : "1/10 N30",
                    "tax_exempt_number" : "3142088",
                    "ack_fax_number" : "14102475476",
                    "delivery_time1" : "1000",
                    "credit_limit" : 15000,
                    "delivery_time2" : "700",
                    "rec_update_date" : "2016-01-14",
                    "customer_type_code" : "A",
                    "account_id" : "WA0477",
                    "msa_secret" : 0,
                    "status" : "A",
                    "taxable" : 0,
                    "delivery_day1" : "Monday",
                    "msp_block" : 1,
                    "delivery_day2" : "Monday",
                    "account_name" : "#020 BALTIMORE MD",
                    "accounts_id" : 1752,
                    "wizard_trained" : 1,
                    "how_ship" : "Our Truck",
                    "addresses" : [ 
                        {
                            "bill_to_addr_orig_system_ref" : "WA0477-0000-036",
                            "bill_to_cust_orig_system" : "NC",
                            "shipping_instructions" : "\r\n",
                            "ship_to_flag" : "N",
                            "bill_to_cust_org_sys_ref" : "WA0477-036",
                            "state" : "MD",
                            "address1" : "5800 COLUMBIA PARK RD",
                            "bill_to_addr_orig_system" : "NC",
                            "address_status" : "A",
                            "city" : "CHEVERLY",
                            "orig_system_ship_customer" : "NC",
                            "division" : "36",
                            "bill_to_cust_orig_system_ref" : "WA0477-036",
                            "bill_to_addr_org_sys" : "NC",
                            "primary_flag" : 0,
                            "oracle_account_number" : "6257",
                            "orig_system_ship_customer_ref" : "WA0477-036",
                            "org_system_ship_customer_ref" : "WA0477-036",
                            "bill_to_addr_org_sys_ref" : "WA0477-0000-036",
                            "division_code" : "36",
                            "addressid" : "4910",
                            "account_number" : "6257",
                            "modify_date" : "2008-02-29",
                            "oracle_account_name" : "ABC SUPPLY CO INC",
                            "bill_to_cust_org_sys" : "NC",
                            "org_system_ship_customer" : "NC",
                            "country" : "US",
                            "ship_id" : "0",
                            "county" : "PRINCE GEORGES",
                            "postal_code" : "20785",
                            "trans_type" : "S",
                            "bill_to_flag" : "Y",
                            "legacy_account" : "WA0477-036"
                        }
                    ],
                    "po_approval_amount" : 20000,
                    "on_line" : 1,
                    "store_xref" : "WA0477",
                    "address_id" : 2900,
                    "plant_id" : 1,
                    "shipping_address_id" : 0,
                    "energy_up_charge" : 0,
                    "rebate" : "N",
                    "norrey_edi" : 0,
                    "cutoff2" : 9,
                    "cutoff1" : 9,
                    "buyers_name" : "Jerry Gorombol",
                    "ship_code" : 0,
                    "ftp_password" : "awd0430",
                    "credit_consolidation" : "WA0460",
                    "plan_region" : "M3",
                    "thermal_delivery2" : 0,
                    "inv_fax_number" : "3013869312",
                    "price_code" : "C",
                    "thermal_delivery1" : 0,
                    "fob" : "DELIVERED",
                    "route" : "34770",
                    "thermal_cutoff2" : 0,
                    "thermal_cutoff1" : 0,
                    "dist_type" : "D1",
                    "ship_xref" : "WA0477",
                    "shipping_inst_id" : 0,
                    "delivery1" : 2,
                    "mkt_type" : "NC3",
                    "msp_allowance" : 2728,
                    "delivery2" : 2
                },{
                    "bill_to" : "WA0477",
                    "print_lines" : "B",
                    "phone_number" : "4102472424",
                    "ftp_user_id" : "abcsup",
                    "terms" : "1/10 N30",
                    "tax_exempt_number" : "3142088",
                    "ack_fax_number" : "14102475476",
                    "delivery_time1" : "1000",
                    "credit_limit" : 15000,
                    "delivery_time2" : "700",
                    "rec_update_date" : "2016-01-14",
                    "customer_type_code" : "A",
                    "account_id" : "WA0477",
                    "msa_secret" : 0,
                    "status" : "A",
                    "taxable" : 0,
                    "delivery_day1" : "Monday",
                    "msp_block" : 1,
                    "delivery_day2" : "Monday",
                    "account_name" : "#020 BALTIMORE MD",
                    "accounts_id" : 1752,
                    "wizard_trained" : 1,
                    "how_ship" : "Our Truck",
                    "addresses" : [ 
                        {
                            "bill_to_addr_orig_system_ref" : "WA0477-0000-036",
                            "bill_to_cust_orig_system" : "NC",
                            "shipping_instructions" : "\r\n",
                            "ship_to_flag" : "N",
                            "bill_to_cust_org_sys_ref" : "WA0477-036",
                            "state" : "MD",
                            "address1" : "5800 COLUMBIA PARK RD",
                            "bill_to_addr_orig_system" : "NC",
                            "address_status" : "A",
                            "city" : "CHEVERLY",
                            "orig_system_ship_customer" : "NC",
                            "division" : "36",
                            "bill_to_cust_orig_system_ref" : "WA0477-036",
                            "bill_to_addr_org_sys" : "NC",
                            "primary_flag" : 0,
                            "oracle_account_number" : "6257",
                            "orig_system_ship_customer_ref" : "WA0477-036",
                            "org_system_ship_customer_ref" : "WA0477-036",
                            "bill_to_addr_org_sys_ref" : "WA0477-0000-036",
                            "division_code" : "36",
                            "addressid" : "4910",
                            "account_number" : "6257",
                            "modify_date" : "2008-02-29",
                            "oracle_account_name" : "ABC SUPPLY CO INC",
                            "bill_to_cust_org_sys" : "NC",
                            "org_system_ship_customer" : "NC",
                            "country" : "US",
                            "ship_id" : "0",
                            "county" : "PRINCE GEORGES",
                            "postal_code" : "20785",
                            "trans_type" : "S",
                            "bill_to_flag" : "Y",
                            "legacy_account" : "WA0477-036"
                        }
                    ],
                    "po_approval_amount" : 20000,
                    "on_line" : 1,
                    "store_xref" : "WA0477",
                    "address_id" : 2900,
                    "plant_id" : 1,
                    "shipping_address_id" : 0,
                    "energy_up_charge" : 0,
                    "rebate" : "N",
                    "norrey_edi" : 0,
                    "cutoff2" : 9,
                    "cutoff1" : 9,
                    "buyers_name" : "Jerry Gorombol",
                    "ship_code" : 0,
                    "ftp_password" : "awd0430",
                    "credit_consolidation" : "WA0460",
                    "plan_region" : "M3",
                    "thermal_delivery2" : 0,
                    "inv_fax_number" : "3013869312",
                    "price_code" : "C",
                    "thermal_delivery1" : 0,
                    "fob" : "DELIVERED",
                    "route" : "34770",
                    "thermal_cutoff2" : 0,
                    "thermal_cutoff1" : 0,
                    "dist_type" : "D1",
                    "ship_xref" : "WA0477",
                    "shipping_inst_id" : 0,
                    "delivery1" : 2,
                    "mkt_type" : "NC3",
                    "msp_allowance" : 2728,
                    "delivery2" : 2
                }
            ],
            "customers_id" : 444,
            "customer_name" : "ABC SUPPLY",
            "customer_type" : "Ellison",
            "customer_id" : "X_WA",
            "parent_id" : "-",
            "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis nisi quis mi tincidunt luctus ut quis nunc. Nam non risus tincidunt risus sodales condimentum. Morbi sed gravida elit. Nunc a turpis vestibulum elit posuere blandit. Phasellus luctus lectus non porta auctor. Etiam pellentesque imperdiet posuere. Nullam adipiscing congue nisl, in vulputate odio ornare ac."        
        }
    ];
  });
